name: naverland-open

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # UTC 자정 = KST 오전 9시

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run crawler (headed via xvfb)
        run: |
          sudo apt-get update && sudo apt-get install -y xvfb
          xvfb-run -a python crawl_open.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: naverland-state
          path: |
            .artifacts/state.png
            .artifacts/state.html
